/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Main', {
	extend: 'Ext.tab.Panel',

	config: {
		items: [
			{
				xtype: 'panel',
				title: 'Budget',
				items: [
					{
						xtype: 'textfield',
						label: 'Total:',
						labelWidth: '40%'
					},
					{
						xtype: 'textfield',
						label: 'Spent:',
						labelWidth: '40%'
					},
					{
						xtype: 'textfield',
						label: 'Remaining:',
						labelWidth: '40%'
					},
					{
						xtype: 'sliderfield',
						label: ''
					},
					{
						xtype: 'image',
						border: '2px dashed black',
						height: '200px',
						minHeight: '',
						minWidth: '',
						width: '300px',
						src: 'chart.png'
					}
				]
			},
			{
				xtype: 'panel',
				title: 'Expenses',
				items: [
					{
						xtype: 'list',
						itemTpl: [
							'<div>List Item {string}</div>'
						]
					}
				]
			},
			{
				xtype: 'panel',
				title: 'Entry',
				items: [
					{
						xtype: 'fieldset',
						height: 433,
						margin: '',
						width: 313,
						title: 'Expense Entry',
						items: [
							{
								xtype: 'spinnerfield',
								border: '',
								margin: '10px 5px 10px 5px',
								label: '$',
								labelWidth: '15%',
								maxValue: 10000,
								minValue: 0,
								stepValue: 0.01,
								defaultValue: 0,
								increment: 0.01
							},
							{
								xtype: 'selectfield',
								margin: '10px 5px 10px 5px',
								label: '',
								labelWidth: 0,
								placeHolder: 'category'
							},
							{
								xtype: 'textareafield',
								margin: '10px 5px 10px 5px',
								label: '',
								labelWidth: 0,
								placeHolder: 'Details'
							},
							{
								xtype: 'button',
								left: '',
								margin: '10px 5px 10px 5px',
								padding: 0,
								right: '',
								width: 150,
								text: 'Take Photo'
							},
							{
								xtype: 'button',
								height: 37,
								margin: '10px 5px 10px 5px',
								text: 'Save'
							}
						]
					}
				]
			}
		]
	}

});